source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in exchange.gemspec.
gemspec

gem "puma"

gem "sqlite3"

gem "sprockets-rails"

gem 'faye-websocket', '~> 0.11.3'
gem 'eventmachine', '~> 1.2', '>= 1.2.7'
gem 'connection_pool', '~> 2.4', '>= 2.4.1'

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
